AWSTemplateFormatVersion: '2010-09-09'
Description: Creates an S3 bucket for storing and serving item images in the AI Scrapyard game. This bucket is used to store all item images that players can find and collect in the game, with versioning enabled for image history tracking.

Resources:
  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref ImagesLoggingBucket
        LogFilePrefix: images-access-logs/

  ImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !GetAtt ImagesBucket.Arn
              - !Sub "${ImagesBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

  ImagesLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ImagesLoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ImagesLoggingBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !GetAtt ImagesLoggingBucket.Arn
              - !Sub "${ImagesLoggingBucket.Arn}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false"

Outputs:
  ImagesBucketName:
    Description: Name of the images S3 bucket
    Value: !Ref ImagesBucket
    Export:
      Name: !Sub "${AWS::StackName}-ImagesBucketName"
  ImagesBucketArn:
    Description: ARN of the images S3 bucket
    Value: !GetAtt ImagesBucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ImagesBucketArn"
  ImagesLoggingBucketName:
    Description: Name of the images logging S3 bucket
    Value: !Ref ImagesLoggingBucket
    Export:
      Name: !Sub "${AWS::StackName}-ImagesLoggingBucketName"
  PlaceholderOutput:
    Description: Placeholder output value
    Value: "placeholder-s3-bucket-value"
  
