name: Build Spirit of Kiro with Godot 4.4.1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Godot 4.4.1 headless
      uses: firebelley/setup-godot@v1
      with:
        godot-version: 4.4.1
        headless: true

    - name: Create build folder
      run: mkdir -p build

    - name: Export project for Windows Desktop
      run: godot --export "Windows Desktop" build/spirit_of_ki

