name: Release EXE on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload EXE to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/spirit_of_kiro.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
