name: Build Spirit of Kiro Windows Export

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create build folder
        run: mkdir -p build/

      - name: List build folder (empty for now)
        run: ls -l build/
