name: Package and Upload Build

on:
  workflow_dispatch:  # می‌تونی دستی از GitHub اجراش کنی

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP from build folder
        run: |
          mkdir -p build
          zip -r spirit_of_kiro_windows.zip build/

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: spirit_of_kiro_build
          path: spirit_of_kiro_windows.zip
