name: Build and Package Windows EXE

on:
  workflow_dispatch:  # اجرا دستی از UI
  push:
    branches:
      - main           # اجرا هنگام push روی main

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Godot 4.4.1 headless
        run: |
          wget https://downloads.tuxfamily.org/godotengine/4.4.1/Godot_v4.4.1-stable_linux_headless_amd64.zip
          unzip Godot_v4.4.1-stable_linux_headless_amd64.zip -d godot
          chmod +x godot/Godot_v4.4.1-stable_linux_headless_amd64

      - name: Make build folder
        run: mkdir -p build/

      - name: Export Windows build
        run: |
          ./godot/Godot_v4.4.1-stable_linux_headless_amd64 \
            --headless \
            --export-release "Windows Desktop" build/spirit_of_kiro.exe

      - name: Zip EXE
        run: zip -j spirit_of_kiro_windows.zip build/spirit_of_kiro.exe

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: spirit_of_kiro_exe_zip
          path: spirit_of_kiro_windows.zip

